module.exports = [
    { name: "Artikelregister - artiklar", url: "https://rms.dev.caspeco.net/prim/articles" },
    { name: "Artikelregister - kattegorier", url: "https://rms.dev.caspeco.net/prim/categories" },
    { name: "Översikt", url: "https://rms.dev.caspeco.net/dashboard"},
    {name: "Personal - Lön - Listor", url: "https://reverseproxy-cloud.dev.caspeco.net/payroll/lists"},
    {name: "Personal - Dokument", url: "https://reverseproxy-cloud.dev.caspeco.net/communication/documents"},
    {name: "Bokning - Bokningar", url: "https://rms.dev.caspeco.net/booking/timetable/"},
    {name: "Bokning - Kommunikation", url: "https://rms.dev.caspeco.net/booking/timetable/"},
    {name: "Bokning - Administrera", url: "https://rms.dev.caspeco.net/booking/administration/webrules"},
    {name: "Bokning - Filmer", url: "https://rms.dev.caspeco.net/booking/support/videos/"},
    {name: "Analys - översikt", url: "https://reverseproxy-cloud.dev.caspeco.net/air/landingPage"},
    {name: "Analys - filmer", url: "https://reverseproxy-cloud.dev.caspeco.net/support/videos"},
    {name: "Analys - utfall", url:"https://reverseproxy-cloud.dev.caspeco.net/air/result"},
    {name: "Analys - editera dashboards", url: "https://reverseproxy-cloud.dev.caspeco.net/air/dashboard"},
    {name: "Analys - rapporter", url: "https://reverseproxy-cloud.dev.caspeco.net/reports/reportgenerator"},
    {name: "Analys - ändra rapporter", url: "https://reverseproxy-cloud.dev.caspeco.net/reports/edittemplate"},
    {name: "Analys - datakällor", url: "https://reverseproxy-cloud.dev.caspeco.net/reports/dynamicdataprovider"},
    {name: "Mina sidor - profil", url: "https://reverseproxy-cloud.dev.caspeco.net/me/profile"},
    {name: "Mina sidor - meddelanden", url: "https://reverseproxy-cloud.dev.caspeco.net/communication/inbox"},
    {name: "Kampanjer", url: "https://reverseproxy-cloud.dev.caspeco.net/checkoutMenu/campaigns"},
    {name: "Kassa - översikt", url: "https://rms.dev.caspeco.net/checkout/merchant/edit/1b283005-f965-4d66-a8e4-139ec711277e/stats"},
    {name: "Kassa - platser", url: "https://rms.dev.caspeco.net/checkout/places/list"},
    {name: "Kassa - menyer", url: "https://rms.dev.caspeco.net/checkout/menu/list?merchantId=1b283005-f965-4d66-a8e4-139ec711277e"},
    {name: "Kassa - redovisning", url: "https://rms.dev.caspeco.net/checkout/settings/accounting"},
];